version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meudb
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database:/docker-entrypoint-initdb.d

volumes:
  postgres_data: 